id: I373ED49C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:03:20+00:00'
last_modified: '2022-06-07T14:11:36.619837+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD416
  title: བསྟན་པའི་ཤན་འབྱེད་འཕྲུལ་གྱི་མེ་ལོང་རབ་གསལ་སྒྲོན་མེ་སོགས། （ལོ་རྒྱུས་སྐོར།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C722:
      image_group_id: I4PD4686
      title: ''
      total_pages: 360
      order: 1
      base_file: C722.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
